### ISSUE TITLE
Erreur Cureos.Measures - fonctions stacking dans Packlib

### ISSUE THREAD

**Issue by anobre** [treeDiM/PLMPackLib#112]
Quelque soit les fonctions de regroupement, (etuis/caisse/palette, bundle/palette, bundle/caisse) le message suivant apparait :
![image](https://cloud.githubusercontent.com/assets/5347239/6231343/75c1cff4-b6c6-11e4-8b71-a65211d6d4a2.png)

**Comment by fgasnier71** [comment]
See StackBuilder GUIExtensionExt.msm
