### ISSUE TITLE
 l'Outil .dll pour éditer une dll n’apparaît plus 

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#116]
Lorsque l'on active les outils de débogage, l'outils .dll (éditer un composant) n’apparaît pas dans la barre d'outil. (depuis que tous les outils sont sur une seule barre d'outil)

**Comment by fgasnier71** [comment]
See issue #107.
Comme convenu l'outil .dll n'apparaît plus dans la barre d'outil unique. cf @anobre
