### ISSUE TITLE
Mise à jour par Patch 

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#117]
Dans la mesure du possible faire les mises à jour de PackLib par téléchargement de patch successif

Par exemple:
7.0.0.16 pre-release 

7.0.(1).0 mise à jour par patch
7.0.(2).0

7.(1).0.0 Mise à jour manuelle

Si possible le téléchargement se fait à l'ouverture de PackLib
Le patch doit respecter le répertoire d'installation, version PLM ou Picador

Cette fonctionnalité apporterai beaucoup au client, les mises à jour sont actuellement trop laborieuses. 

Est ce que cela est réalisable?
@anobre @fgasnier71

**Comment by fgasnier71** [comment]
A priori, le but étant de passer rapidement à une version client léger qui s'actualise à chaque lancement de l'application (installation ClickOnce) avec toutes les données hébergées sur le cloud, cette issue ne comporte pas d'intérêt. Je ferme.
