### ISSUE TITLE
Urgent Install Picador/PackLIB v8

### ISSUE THREAD

**Issue by anobre** [treeDiM/PLMPackLib#129]
PACKLIB v8
-	Changer le numéro de version : 8.0  (FGA)
-	Nouvelle Base de données (PBU -  1 base full pour Picador / 1 base pour PackLIB free)
-	Pouvoir ouvrir PackLIB directement sur la commande « PLM Start » (Root) (FGA)
-	Générer MSM (FGA)
-	Install : Changer le numéro de série : FX16VR80ZH08  (Wix FGA – IS ANO)

**Comment by fgasnier71** [comment]
L'issue est mal faite dans le sens elle s'adresse obligatoirement à plusieurs participants et qu'elle regroupe plusieurs tâches qui n'ont rien à voir les unes avec les autres.
