### ISSUE TITLE
Install V8

### ISSUE THREAD

**Issue by anobre** [treeDiM/PLMPackLib#133]
PLMPackLibMSM_woDatabase.msm  : 
- Changer le sous-répertoire de destination Bin32 en Bin8_2D
- Ne pas mettre dans cette install le fichier PLMPackLib.exe.config
- Mettre à jour avec la dernière version de Localisation_FRA.txt

StackBuilderGUIExtMSM.msm 
- Changer le sous-répertoire de destination Bin32 en Bin8_2D
- Changer le Num de version en 8.0

Pic3DExporterMSM.msm 
- Changer le sous-répertoire de destination Bin32 en Bin8_2D
- Changer le Num de version en 8.0

**Comment by fgasnier71** [comment]
Où est la dernière version du fichier Localisation_FRA.txt?
Dans les sources, le fichier est daté du vendredi ‎7 ‎mars ‎2014, ‏‎17:28:48.
