### ISSUE TITLE
SUMA version : icône + splash

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#136]
![suma](https://cloud.githubusercontent.com/assets/5374935/12417405/2ee49914-bea8-11e5-87c3-438c987477c1.png)

![splash-packlib-suma](https://cloud.githubusercontent.com/assets/5374935/12417478/a7c20fc4-bea8-11e5-82d1-13c00a8ed3ef.png)

**Comment by fgasnier71** [comment]
@pbuffet Le nom de la marque SUMMA est écrit avec un seul M sur l'icône. Est-ce normal?

**Comment by pbuffet** [comment]
![suma](https://cloud.githubusercontent.com/assets/5374935/12421955/d26c0d26-bec4-11e5-8f05-2874a2386bce.png)

bien vu,
