### ISSUE TITLE
Affichage des entités cotation et axe

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#141]
![annotation01](https://cloud.githubusercontent.com/assets/5374935/15219477/3a9da2d0-1864-11e6-9591-19e36c554967.png) Lorsque cette fonction est active: toutes les entités du code en type de trait cotation et axe apparaissent dans l'affichage du plan. Pas les cotations
Lors de l'export, les élément sont également apparent sur le fichier.

![image](https://cloud.githubusercontent.com/assets/5374935/15220261/1b78727e-1867-11e6-8233-c35bfa7de847.png)

**Comment by fgasnier71** [comment]
See issue #148
