### ISSUE TITLE
Affichage des dimensions

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#142]
![annotation02](https://cloud.githubusercontent.com/assets/5374935/15220331/6927379e-1867-11e6-93e8-5783576dae4e.png) Lorsque que cette icône est active, les cotations présentes dans le code s'affichent sur le plan et sont apparentes lors d'un export ou de l'ouverture dans Picador

![image](https://cloud.githubusercontent.com/assets/5374935/15220336/6b454a98-1867-11e6-9dc1-eaef192dab34.png)

**Comment by fgasnier71** [comment]
See issue #148
