### ISSUE TITLE
Ecraser les format et profils cartons si différents lors de l'import/mise à jour

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#145]
Lors de l'import d'une base ou du téléchargement et mise à jour, écraser les profils cartons et les formats cartons existant si ils ont le même nom/designation.
![image](https://cloud.githubusercontent.com/assets/5374935/16145054/419f9e4c-3477-11e6-90a6-7c13385b21c8.png)

**Comment by fgasnier71** [comment]
* Se renseigner auprès d'@anobre pour savoir si on souhaite toujours maintenir cette version.
