### ISSUE TITLE
bug - Export cotations automatiques 

### ISSUE THREAD

**Issue by pbuffet** [treeDiM/PLMPackLib#151]
lorsque l'on export les cotations automatiques, il y à des cotations obliques supplémentaires qui apparaissent sur le document exporté

![image](https://cloud.githubusercontent.com/assets/5374935/22020547/32850326-dcb9-11e6-9d37-c88d84ae795e.png)

bug visible sur tous les documents.

**Comment by fgasnier71** [comment]
Afin de reproduire le bug, quel est le composant utilisé?

**Comment by pbuffet** [comment]
Utilise le FEFCO demo/fefco 200

Mais globalement cela apparaît sur tous les modèles
