### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by yeutinh** [treeDiM/PLMPackLib#152]
Dear team,

I checked out the new version, I think it is quite a significant improvement on stability.

The new layout is also more cleaned.

But cannot run the apps offline mode. 

Is there any plan for it to run offline like the previous version ?

Thanks

Luan

**Comment by fgasnier71** [comment]
The main goal of development in recent version is to get rid of the local database and replace it with a cloud database. This makes both deployment and maintenance much easier.
Also, we plan to create a website that will use the same database.

There is no plan for the moment to offer an offline mode as we believe the majority of customers are using our products when connected. Some customers (for StackBuilder) told us about some company policy that prevents users from connecting to a cloud.
Is it also the reason why you need an offline mode?
Regards,

**Comment by yeutinh** [comment]
There are part of the plant I work in that have no connection, for safety
reason. It's explosion shielded and no mobile anything wireless.

When you take the laptop around, it has to be disconnected.

Also, the internet in Australia is atrocious, going offline all the time
even in the main city. Nothing like EU or US.

Other than that, I don't use database anyway as I use StackBuilder and
Packlib for concept design feasibility. If something seem to be feasible,
the parameters is transfer to continental design teams to create.

Cheers
