### ISSUE TITLE
Imposition

### ISSUE THREAD

**Issue by anobre** [treeDiM/PLMPackLib#155]
Si il y a des entités dont l'attribut type de trait est > 8 :
- l'export direct Picador supprime ces types de traits
- l'export Picador après imposition supprime tout le dessin sauf le format carton.

Document test : V&R FLOWER

[V&R FLOWER BOMB 140917 unitaire.zip](https://github.com/treeDiM/PLMPackLib/files/1387961/V.R.FLOWER.BOMB.140917.unitaire.zip)

**Comment by fgasnier71** [comment]
* Ne plus publier d'issue pour PLMPackLib...
* Issue corrigée sur PLMPack (cf PicVisitorDesOutput.LineTypeToDesPen())
