### ISSUE TITLE
Imposition with small arcs

### ISSUE THREAD

**Issue by anobre** [treeDiM/PLMPackLib#156]
Lorsque l'on réalise une imposition avec des arcs de rayon < 0.5 , les arcs sont inversés.
Testés : le même arc avec un rayon > 0.5, c'est ok.
_(Idem imposition Auto dans Picador)_
Document TEST ARCS
[test_arcs.zip](https://github.com/treeDiM/PLMPackLib/files/1388098/test_arcs.zip)

**Comment by fgasnier71** [comment]
Ne plus créer d'issue dans PLMPackLib mais [ici.](https://github.com/anobre/PLMPack/issues)
