### ISSUE TITLE
Azure : Réfléchir à une solution de base de donnée sous azure

### ISSUE THREAD

**Issue by fgasnier71** [treeDiM/PLMPackLib#86]
* L'idée est de ne plus recourir à l'utilisation de fichier archive (*.zip) pour l'installation de nouveau composants.
L'arborescence présente toutes les données mais chaque fichier/composant n'est en fait téléchargé qu'à la première utilisation.
* Réfléchir à l'utilisation d'une base de données centralisée pour la sauvegarde des majorations/matériaux qui sont des données utilisateurs.
* Après installation, aucun composant n'est installé localement,
* L'utilisateur ne peut modifier que sa propre branche,
* L'upload de fichier par l'utilisateur ne s'effectue que suite à une action voulue pour qu'il est conscience du fait qu'il a uploader un document

**Comment by pbuffet** [comment]
Projet PackLib Azure ouvert
